name: CI

env:
  DIR_API: "api"
  DIR_SITE: "site"
  DIR_INT: "integration"
  ART_API: "api-${{github.sha}}"
  ART_SITE: "site-${{github.sha}}"

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-api:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Restore dependencies
      run: dotnet restore
      working-directory: ${{env.DIR_API}}
      
    - name: Build
      run: dotnet build --no-restore
      working-directory: ${{env.DIR_API}}
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ${{env.DIR_API}}

    - name: Create artifacts
      uses: actions/upload-artifact@v2
      with:
        name: "${{env.ART_API}}"
        path: "${{env.DIR_API}}/bin/Debug/net5.0/**"

  build-site:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'
        cache-dependency-path: "./${{env.DIR_SITE}}"
    
    - name: Install dependencies
      run: npm ci
      working-directory: ${{env.DIR_SITE}}
    
    - name: Test
      run: npm run test:ci
      working-directory: ${{env.DIR_SITE}}

    - name: Build
      run: npm run build
      working-directory: ${{env.DIR_SITE}}
    
    - name: Create artifacts
      uses: actions/upload-artifact@v2
      with:
        name: "${{env.ART_SITE}}"
        path: "${{env.DIR_SITE}}/build"

  test-integration:
    runs-on: ubuntu-latest
    needs: [build-api, build-site]
    
    steps:
    - uses: actions/checkout@v2
      with:
        path: git
    
    - uses: actions/download-artifact@v2
      with:
        name: ${{env.ART_API}}
        path: ${{env.DIR_API}}

    - uses: actions/download-artifact@v2
      with:
        name: ${{env.ART_SITE}}
        path: ${{env.DIR_SITE}}

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'
        cache-dependency-path: "./git/${{env.DIR_INT}}"
    
    - name: Install dependencies
      run: npm i
      working-directory: "git/${{env.DIR_INT}}"

    - name: Test
      run: npm test
      working-directory: "git/${{env.DIR_INT}}"

    - name: Display structure of downloaded files
      run: ls -R
