name: .NET

env:
  DIR_API: "api"
  DIR_SITE: "site"
  ART_API: "api-${{github.sha}}"
  ART_SITE: "api-${{github.sha}}"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-dotnet:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Restore dependencies
      run: dotnet restore
      working-directory: "${{env.DIR_API}}"
      
    - name: Build
      run: dotnet build --no-restore
      working-directory: "${{env.DIR_API}}"
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: "${{env.DIR_API}}"

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: "${{env.ART_API}}"
        path: "${{env.DIR_API}}/bin/Debug/net5.0/**"
