name: CI

env:
  DIR_API: "api"
  DIR_SITE: "site"
  DIR_INT: "integration"
  ART_API: "api-${{github.sha}}"
  ART_SITE: "site-${{github.sha}}"

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test-integration:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        path: git
    
    - uses: actions/download-artifact@v2
      with:
        name: ${{env.ART_API}}
        path: ${{env.DIR_API}}

    - uses: actions/download-artifact@v2
      with:
        name: ${{env.ART_SITE}}
        path: ${{env.DIR_SITE}}

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'
        cache-dependency-path: "./git/${{env.DIR_INT}}"
    
    - name: Install dependencies
      run: npm i
      working-directory: "git/${{env.DIR_INT}}"

    - name: Test
      run: npm test
      working-directory: "git/${{env.DIR_INT}}"

    - name: Display structure of downloaded files
      run: ls -R
